version: "3.8"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/auth-service
      JWT_SECRET: "your_secret_key"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
