apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: energy-service
  template:
    metadata:
      labels:
        app: energy-service
    spec:
      containers:
        - name: energy-service
          image: your-dockerhub-username/energy-service:latest
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: energy-config
---
apiVersion: v1
kind: Service
metadata:
  name: energy-service
spec:
  type: ClusterIP
  selector:
    app: energy-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
